# Constants
NUM_BOIDS = 60
MAX_SPEED = 0.1
MIN_SPEED = 0.05  # Minimum speed to prevent boids from stopping
MAX_FORCE = 0.01
NEIGHBOURHOOD_RADIUS = 2.5

# Cuboid dimensions (12x9x9)
X_LIMIT = 6  # Half of 12
Y_LIMIT = 4.5  # Half of 9
Z_LIMIT = 4.5  # Half of 9

POSITIVE_LIMIT = X_LIMIT
NEGATIVE_LIMIT = -X_LIMIT
POSITIVE_Y_LIMIT = Y_LIMIT
NEGATIVE_Y_LIMIT = -Y_LIMIT
POSITIVE_Z_LIMIT = Z_LIMIT
NEGATIVE_Z_LIMIT = -Z_LIMIT
